# Ticket persistence contract shared by in-memory and PostgreSQL providers.
from typing import Protocol
from app.features.feature_tickets.schemas.ticket_schemas import TicketCreate, TicketView
class TicketStore(Protocol):
    async def ensure_customer(self, email: str) -> int: ...
    async def create(self, payload: TicketCreate, classification: dict, customer_id: int | None = None) -> TicketView: ...
